export const books = [
  {
    "isbn": 2005883,
    "title": "Gilead",
    "authors": "Marilynne Robinson",
    "categories": "Fiction",
    "thumbnail": "http://books.google.com/books/content?id=KQZCPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "A NOVEL THAT READERS and critics have been eagerly anticipating for over a decade, Gilead is an astonishingly imagined story of remarkable lives. John Ames is a preacher, the son of a preacher and the grandson (both maternal and paternal) of preachers. It’s 1956 in Gilead, Iowa, towards the end of the Reverend Ames’s life, and he is absorbed in recording his family’s story, a legacy for the young son he will never see grow up. Haunted by his grandfather’s presence, John tells of the rift between his grandfather and his father: the elder, an angry visionary who fought for the abolitionist cause, and his son, an ardent pacifist. He is troubled, too, by his prodigal namesake, Jack (John Ames) Boughton, his best friend’s lost son who returns to Gilead searching for forgiveness and redemption. Told in John Ames’s joyous, rambling voice that finds beauty, humour and truth in the smallest of life’s details, Gilead is a song of celebration and acceptance of the best and the worst the world has to offer. At its heart is a tale of the sacred bonds between fathers and sons, pitch-perfect in style and story, set to dazzle critics and readers alike.",
    "published_year": 2004,
    "average_rating": 3.85,
    "num_pages": 247,
    "ratings_count": 361,
    "original_price": 20,
    "selling_price": 20
  },
  {
    "isbn": 2261987,
    "title": "Spider's Web",
    "authors": "Charles Osborne;Agatha Christie",
    "categories": "Detective and mystery stories",
    "thumbnail": "http://books.google.com/books/content?id=gA5GPgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "A new 'Christie for Christmas' -- a full-length novel adapted from her acclaimed play by Charles Osborne Following BLACK COFFEE and THE UNEXPECTED GUEST comes the final Agatha Christie play novelisation, bringing her superb storytelling to a new legion of fans. Clarissa, the wife of a Foreign Office diplomat, is given to daydreaming. 'Supposing I were to come down one morning and find a dead body in the library, what should I do?' she muses. Clarissa has her chance to find out when she discovers a body in the drawing-room of her house in Kent. Desperate to dispose of the body before her husband comes home with an important foreign politician, Clarissa persuades her three house guests to become accessories and accomplices. It seems that the murdered man was not unknown to certain members of the house party (but which ones?), and the search begins for the murderer and the motive, while at the same time trying to persuade a police inspector that there has been no murder at all... SPIDER'S WEB was written in 1954 specifically for Margaret Lockwood and opened first at the Theatre Royal Nottingham before moving to the Savoy Theatre in London on 14 December 1954. With THE MOUSETRAP and WI",
    "published_year": 2000,
    "average_rating": 3.83,
    "num_pages": 241,
    "ratings_count": 5164,
    "original_price": 25,
    "selling_price": 24
  },
  {
    "isbn": 6163831,
    "title": "The One Tree",
    "authors": "Stephen R. Donaldson",
    "categories": "American fiction",
    "thumbnail": "http://books.google.com/books/content?id=OmQawwEACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "Volume Two of Stephen Donaldson's acclaimed second trilogy featuing the compelling anti-hero Thomas Covenant.",
    "published_year": 1982,
    "average_rating": 3.97,
    "num_pages": 479,
    "ratings_count": 172,
    "original_price": 30,
    "selling_price": 28
  },
  {
    "isbn": 6178731,
    "title": "Rage of Angels",
    "authors": "Sidney Sheldon",
    "categories": "Fiction",
    "thumbnail": "http://books.google.com/books/content?id=FKo2TgANz74C&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "A memorable, mesmerizing heroine Jennifer -- brilliant, beautiful, an attorney on the way up until the Mafia's schemes win her the hatred of an implacable enemy -- and a love more destructive than hate. A dangerous, dramatic world The Dark Arena of organized crime and flashbulb lit courtrooms where ambitious prosecutors begin their climb to political power.",
    "published_year": 1993,
    "average_rating": 3.93,
    "num_pages": 512,
    "ratings_count": 29532,
    "original_price": 40,
    "selling_price": 36
  },
  {
    "isbn": 6280897,
    "title": "The Four Loves",
    "authors": "Clive Staples Lewis",
    "categories": "Christian life",
    "thumbnail": "http://books.google.com/books/content?id=XhQ5XsFcpGIC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "Lewis' work on the nature of love divides love into four categories; Affection, Friendship, Eros and Charity. The first three come naturally to humanity. Charity, however, the Gift-love of God, is divine, and without this supernatural love, the natural loves become distorted and even dangerous.",
    "published_year": 2002,
    "average_rating": 4.15,
    "num_pages": 170,
    "ratings_count": 33684,
    "original_price": 30,
    "selling_price": 29
  },
  {
    "isbn": 6280935,
    "title": "The Problem of Pain",
    "authors": "Clive Staples Lewis",
    "categories": "Christian life",
    "thumbnail": "http://books.google.com/books/content?id=Kk-uVe5QK-gC&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "\"In The Problem of Pain, C.S. Lewis, one of the most renowned Christian authors and thinkers, examines a universally applicable question within the human condition: If God is good and all-powerful, why does he allow his creatures to suffer pain? With his signature wealth of compassion and insight, C.S. Lewis offers answers to these crucial questions and shares his hope and wisdom to help heal a world hungering for a true understanding of human nature.\"--Amazon.",
    "published_year": 2002,
    "average_rating": 4.09,
    "num_pages": 176,
    "ratings_count": 37569,
    "original_price": 45,
    "selling_price": 45
  },
  {
    "isbn": 6353282,
    "title": "An Autobiography",
    "authors": "Agatha Christie",
    "categories": "Authors, English",
    "thumbnail": "http://books.google.com/books/content?id=c49GQwAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "Donation.",
    "published_year": 1977,
    "average_rating": 4.27,
    "num_pages": 560,
    "ratings_count": 3975,
    "original_price": 40,
    "selling_price": 38
  },
  {
    "isbn": 6380832,
    "title": "Empires of the Monsoon",
    "authors": "Richard Hall",
    "categories": "Africa, East",
    "thumbnail": "http://books.google.com/books/content?id=MuPEQgAACAAJ&printsec=frontcover&img=1&zoom=1&source=gbs_api",
    "description": "Until Vasco da Gama discovered the sea-route to the East in 1497-9 almost nothing was known in the West of the exotic cultures and wealth of the Indian Ocean and its peoples. It is this civilization and its destruction at the hands of the West that Richard Hall recreates in this book. Hall's history of the exploration and exploitation by Chinese and Arab travellers, and by the Portuguese, Dutch and British alike is one of brutality, betrayal and colonial ambition.",
    "published_year": 1998,
    "average_rating": 4.41,
    "num_pages": 608,
    "ratings_count": 65,
    "original_price": 30,
    "selling_price": 29
  }
]